# Generated by Django 2.1.1 on 2018-10-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
