# Generated by Django 2.1.1 on 2018-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_folder_isroot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='update_time',
            new_name='updateTime',
        ),
        migrations.RenameField(
            model_name='documentprofile',
            old_name='like_count',
            new_name='likeCount',
        ),
        migrations.RenameField(
            model_name='documentprofile',
            old_name='view_count',
            new_name='viewCount',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='parent_id',
            new_name='parentId',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='update_time',
            new_name='updateTime',
        ),
        migrations.AddField(
            model_name='document',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
