# Generated by Django 2.1.1 on 2018-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
